name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: neelis
        host: h2938377.stratoserver.net
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www/pokecards.site && ./server_deploy.sh'
